receivers:
  otlp:
    protocols:
      http:

exporters:
  logging:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto
  jaeger:
    endpoint: jaeger:14250

processors:
  batch:
    timeout: 5s
    send_batch_size: 90

extensions:
  health_check:

service:
  extensions: [ health_check ]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ resource, batch ]
      exporters: [zipkin, jaeger,logging ]